### ISSUE TITLE
latest.tar.gz versus .yarn-cache.tgz

### ISSUE THREAD

**Issue by jbruni** [mfornasa/DockerYarn#1]
Did I misunderstood something... or the "latest.tar.gz" we see in this repository is the Yarn cache referenced as ".yarn-cache.tgz" [in the Medium article](https://medium.com/@mfornasa/using-yarn-with-docker-c116ad289d56#119c)?

**Comment by adamdicarlo** [comment]
`latest.tar.gz` is yarn.
